server:
  port: 8202

eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
spring:
  sleuth:
    sampler:
      probability: 1
#spring:
#  zipkin:
#    base-url: http://localhost:9411/
