# 单机
spring:
  application:
    name: eureka-server
server:
  port: 8100
eureka:
  instance:
    hostname: server1
  client:
    #因为该应用为注册中心，所以设置为false，代表不向注册中心注册自己。
    register-with-eureka: false
    #因为是注册中心，职责就是维护服务实力，并不需要去检索服务。所以也设置为false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

